version: '2'

volumes:

  speedtest-data:
  dashboard-data:
  homeassistant-config:

services:

  # speedtest:
  #   build: ./speedtest
  #   container_name: speedtest
  #   privileged: true
  #   network_mode: host
  #   volumes:
  #     - 'speedtest-data:/data'
  #   labels:
  #     io.balena.features.supervisor-api: 1

  # # connector:
  # #   image:  balenablocks/connector
  # #   container_name: connector
  # #   privileged: true
  # #   restart: always
  # #   labels:
  # #     io.balena.features.balena-api: '1'

  # grafana:
  #   build: ./dashboard
  #   container_name: dashboard
  #   restart: always
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - 'dashboard-data:/data'

  # influxdb:
  #   image: influxdb:1.8
  #   container_name: database
  #   restart: always
  #   environment:
  #     - INFLUXDB_DB=balena
  #     - INFLUXDB_USER=balena
  #     - INFLUXDB_ADMIN_ENABLED=true
  #     - INFLUXDB_ADMIN_USER=admin
  #     - INFLUXDB_ADMIN_PASSWORD=admin
  #     - INFLUXDB_DATA_DIR=/data
  #   volumes:
  #     - 'speedtest-data:/data'

  # mosquitto:
  #   image: eclipse-mosquitto
  #   container_name: mqtt-broker
  #   restart: always
  #   ports:
  #     - "1883:1883"

  home-assistant:
    build: ./home-assistant
    container_name: home-assistant
    privileged: true
    restart: unless-stopped
    network_mode: host
    ports: 
      - 8123:8123
    volumes:
      - 'homeassistant-config:/config'

  # overview:
  #   build: ./overview
  #   container_name: overview
  #   restart: always
  #   ports: 
  #     - "80:80"
