version: '2'

volumes:

  homeassistant-config:

services:

  home-assistant:
    build: ./home-assistant
    container_name: home-assistant
    privileged: true
    restart: unless-stopped
    network_mode: host
    ports: 
      - "80:8123"
    volumes:
      - 'homeassistant-config:/config'
