# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Set port
http:
  server_port: 80

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Bose Soundtouch 300
media_player:
  - platform: soundtouch
    host: 192.168.178.88
    port: 8090
    name: Mario Soundbar

# Spotify
spotify:
  client_id: e91857f8248e4e3897f64ca6d14213e6
  client_secret: 6759397f60fe44e2a9e1877e2b641320